### ISSUE TITLE
can you help me? cant add your discord

### ISSUE THREAD

**Issue by yakushevhk** [Goldo02/gif_and_video_art_engine#10]
**my discord yakushevhk#3223**

[gif @ 0x5629d977d640] invalid block label
Input #1, gif, from './layers/2-character/Red_Burning_Woman#80.gif':
  Duration: 00:00:02.40, start: 0.000000, bitrate: 49 kb/s
    Stream #1:0: Video: gif, bgra, 240x240, 10 fps, 10 tbr, 100 tbn, 100 tbc
[gif @ 0x5629d9784fc0] invalid block label
Input #2, gif, from './layers/3-head/Top_Hat#30.gif':
  Duration: 00:00:02.40, start: 0.000000, bitrate: 24 kb/s
    Stream #2:0: Video: gif, bgra, 240x240, 10 fps, 10 tbr, 100 tbn, 100 tbc
Stream mapping:
  Stream #0:0 (gif) -> overlay:main
  Stream #1:0 (gif) -> overlay:overlay
  Stream #2:0 (gif) -> overlay:overlay
  paletteuse -> Stream #0:0 (gif)
Press [q] to stop, [?] for help
[gif @ 0x5629d976c640] invalid block label
Output #0, gif, to './output/media/14.gif':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: gif, pal8, 240x240, q=2-31, 200 kb/s, 10 fps, 100 tbn, 10 tbc (default)
    Metadata:
      encoder         : Lavc58.54.100 gif
Error writing trailer of ./output/media/14.gif: Invalid argument
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by Goldo02** [comment]
i sent u the friend request on discord.

**Comment by Goldo02** [comment]
This guys solved his problem by himself

**Comment by yakushevhk** [comment]
I'll text you soon thank you very much
Not by myself haha you helped me

**Comment by Goldo02** [comment]
Ah nice, how did u solve the error?
