### ISSUE TITLE
Invalid File Index 2 in filtergraph error?

### ISSUE THREAD

**Issue by mrcrayon1** [Goldo02/gif_and_video_art_engine#14]
![image](https://user-images.githubusercontent.com/100059728/155683507-6f0640fa-8949-4e03-abf2-92a9faab8e8e.png)

getting this error when using ./main sol 

This works with other sets of layers I'm using, but not with these! also note that there's only 2 layers with 2 .gifs each. just testing them out. 

really at a loss and anything helps!

ok i added a background folder with 2 backgrounds and that fixed it. I'm not sure what prompted this error in the first place but it isss what it is.

**Comment by Goldo02** [comment]
So u solved this?

**Comment by Goldo02** [comment]
That error was my fault and now should be fixed. Redownload the repo.
