### ISSUE TITLE
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

### ISSUE THREAD

**Issue by Ugijago** [Goldo02/gif_and_video_art_engine#15]
first time i use i have [gif @ 0x55c74bad1a00] invalid block label and Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used) eror show up and the gif corrupted

but after i remove -ss it can run but another error still remain
[gif @ 0x55c74bad1a00] invalid block label for each layer

note : btw i use your original gif
![Screenshot 2022-02-26 012502](https://user-images.githubusercontent.com/97956998/155767957-1a969962-0e05-4176-a1e0-1ed7535cdbac.png)

**Comment by Goldo02** [comment]
Are u using the Ubuntu terminal right?

**Comment by Ugijago** [comment]
> Are u using the Ubuntu terminal right? Did u recompile the code?

yes

**Comment by Ugijago** [comment]
> Can u contact me on discord and send me more info/screenshots?

i just do what you do in tutorial video, exactly the same  nothing i change except -ss in ffmpeg.cpp
![Screenshot 2022-02-27 001025](https://user-images.githubusercontent.com/97956998/155852302-73c5123c-2ce6-442d-ae1c-81c2e994650f.png)

**Comment by Ugijago** [comment]
> So now is working, but u are afraid when generating bigger collection?
ya and just bit perfectionist i dont like work code with weird error still remain(invalid block label)
😊

i search those bug found  team https://trac.ffmpeg.org/ticket/3021 should be fixed by ffmpeg 8 year ago 

 because i do it just like yours in video, its simple, weirdly output different 🤔 so what do you think is wrong ?

so can you fix it?

**Comment by Goldo02** [comment]
it is really strange, have u tryed updating ur ffmpeg version? and what version do u have?

**Comment by Ugijago** [comment]
$ ffmpeg -version
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

**Comment by Goldo02** [comment]
I'm sorry but i don't think i can fix It. I mean on my PC there Isn't this error. This is really strange...

**Comment by Ugijago** [comment]
> 

so what do you think causing invalid block? is it cause by ffmpeg?

**Comment by Goldo02** [comment]
Are u from windows 10 right?

**Comment by Ugijago** [comment]
> Are u from windows 10 right? i would like to investigate more into this, can u add me on discord?

me window 11, i am sorry i dont play discord 😔
just ask what you need i will try post it here 🙏

**Comment by Goldo02** [comment]
I think that's an OS problem. I tryed today on my friend's PC that he has Windows 11 on It and showed the same warning.

**Comment by Ugijago** [comment]
> I think that's an OS problem. I tryed today on my friend's PC that he has Windows 11 on It and showed the same warning. I think there is nothing u can do to don't show this warning. Anyways the code works so ...

ok then so i will close this now 👍
