### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by AkhileshPillai1** [Goldo02/gif_and_video_art_engine#17]
I am having an error while trying to generate gifs. 
![image](https://user-images.githubusercontent.com/76212754/155874006-b4da79bf-a464-4af5-b3d0-414af4389132.png)

**Comment by AkhileshPillai1** [comment]
Can you add me on discord 
Ace_#5831

**Comment by Goldo02** [comment]
can u send me the screenshot of ur main.cpp file?

**Comment by Goldo02** [comment]
Feel free to reopen

**Comment by AkhileshPillai1** [comment]
Hey. Whats ur discord name
