### ISSUE TITLE
Subfolder

### ISSUE THREAD

**Issue by gilnaks** [Goldo02/gif_and_video_art_engine#21]
How to structure subfolder in main cpp? I need to match color for traits

**Comment by Goldo02** [comment]
u need to modify collection size and the layerDir vector. See into the discussion here on github. Link: https://github.com/Goldo02/gif_and_video_art_engine/discussions/13 . I think this can help u

**Comment by gilnaks** [comment]
Hi! I'm trying to achieve something similar to this https://github.com/HashLips/hashlips_art_engine/issues/874

**Comment by Goldo02** [comment]
```
const vector<vector<string>> layerDir = 
{
        {"./1-Background/A", "./2-Skin/A", "./3-Trousers/B", "./4-Cloth/B", "./5-Eyes/A", "./6-Mouth/A", "./7-Face/B", "./8-BottomCostume/C", "./9-Headcostume/A"}
};

I think u can do this the same way Hashlips did, by changing the values in layerDir
```
