### ISSUE TITLE
Help creating .mp4 with sound.

### ISSUE THREAD

**Issue by xBuddhaSupreme** [Goldo02/gif_and_video_art_engine#23]
Thanks for this repository. I am currently trying to get it working. I am getting the gifs to come out properly but having trouble when trying to add the audio. Maybe a little more detail on that process would help. It seems the tutorial video - which I watched - did not cover that section. Also, is there any way for me to autoloop the final .mp4?

Thanks bro, much luv!

I added you on Discord, please accept my friend request.

**Comment by Goldo02** [comment]
Wait i'm not understanding. U can't have gifs with audio, but u can have the audio if u use mov files. U can't use MP4 files because, MP4 Is not a transparent format. Whats ur name on discord?

**Comment by xBuddhaSupreme** [comment]
xBuddhaSupreme#9448. I am out now but I am in the process of converting to .mov to see if I can make it work. I still don’t understand the file structure/tmp file situation.

**Comment by xBuddhaSupreme** [comment]
I was definitely trying to combine gifs and mp3 tho. 😅

**Comment by Goldo02** [comment]
Okey i can explain u that, but can u explain me what do u want to do exactly? If the mov files have an audio trace u just need to run the code with mov files as layers. Then the output will have the audio trace overlapped.

**Comment by xBuddhaSupreme** [comment]
Sorry I have been spending the day trying to convert my gif attributes to transparent .mov which isn't as straight forward as it seems for some reason. I did end up doing a run and it failed, but ironically it's because I need more storage space. I don't know how big the final file will be but I will have more to say tomorrow evening. I think I may be on the right track, I really appreciate your guidance!
