### ISSUE TITLE
collectionSize

### ISSUE THREAD

**Issue by khangtrn96** [Goldo02/gif_and_video_art_engine#24]
I have some problems:
1. I have edited value of "vector<int> collectionSize = {}", but it always exports 31 gifs.
2. I want the first gif is numbered 1 instead of 0.
3. I don't see "src" folder in your git file. How can I find it?

Thanks so much !
Can you add my discord: **khangtrn96#3247**

**Comment by Goldo02** [comment]
Redownload the repo. I have already added u
