### ISSUE TITLE
vector<int> collectionSize = {x,y,z}; Are more than two different combinations of the layers possible?

### ISSUE THREAD

**Issue by JuiceGoose1** [Goldo02/gif_and_video_art_engine#25]
Hello!

Thank you for making this code, I've been using it to make some cool stuff. Is that metamask address 0xaE9d8FD177c22D88159F2773998dB07CAf40693d up to date? I would like to send you an NFT to say thank you. I have sent you a discord friend invite: JuiceGoose#3498.

I am a programming noob, I wanted to know if it is possible to make more than just 2 of the collectionsize layer combinations. For example vector<int> collectionSize = {w,x,y,z}; to create 4 different combinations of the layers? This would be incredibly useful to have. Currently when I try I get a segfault.

Thank you for your help.

**Comment by Goldo02** [comment]
Yep that's is possible. It's strange u are getting a segmentation fault. Check the layerDir vector
