### ISSUE TITLE
Issue when trying to compile myFFmpegConversion.ccp

### ISSUE THREAD

**Issue by Westy-Dev** [Goldo02/gif_and_video_art_engine#6]
There is an issue when trying to compile myFFmpegConversion.ccp

There is an undefined reference to extractInteger on line 155 which is causing it to not compile - am I missing something?

I have the latest version of the repo and I am using Linux on Windows.

Many thanks for this repo!

**Comment by Goldo02** [comment]
It is strange. Contact me on discord

**Comment by Westy-Dev** [comment]
fifone#2742 doesn't work, I can't add it
