### ISSUE TITLE
Conversion not precise and timings are completely off

### ISSUE THREAD

**Issue by jozkr8** [Goldo02/gif_and_video_art_engine#8]
The combined .mp4 from gifs isn't the same size as the output:

For example - the input gifs have 2.3s and the combined .mp4 file has 2.4s whilst the exported gif has 2.14s. So this is not matching frames during the process. Attaching the screen:

<img width="822" alt="conersion-not-exact" src="https://user-images.githubusercontent.com/67471660/155180429-1729a52a-cd49-417f-9694-5f4706e99001.png">

**Comment by Goldo02** [comment]
This problem was solved, for conversion of the same type, for example from gif to gif and from mov to mov there are no problema, but from mov to gif seems like there Is some delay, this however is negligible.
