### ISSUE TITLE
It zooms the layers, stops the gif after 1 second

### ISSUE THREAD

**Issue by kisbalazspatrik** [Goldo02/gif_and_video_art_engine#9]
Hi!

So i've got a 5second gif for background, and all the other layers are PNGs.
It just zooms in a lot for the pngs, even if i modify the scale, what could be the problem? And it resets after 1 second.

(All the layers are the same size)

**Comment by Goldo02** [comment]
Can u try with the new code?

**Comment by Goldo02** [comment]
Feel free to reooen
